# build stage
FROM node:22-alpine AS build

WORKDIR /profilerInsight
COPY package*.json ./
RUN npm install
COPY . /profilerInsight
RUN npm run build

# production stage
FROM nginx:stable-alpine AS production-stage
COPY --from=build /profilerInsight/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]