# build stage
FROM node:lts-alpine AS build-stage

ARG VUE_APP_FRONTEND_HOST
ARG VUE_APP_FRONTEND_PORT
ARG VUE_APP_FLASK_HOST
ARG VUE_APP_FLASK_PORT

ENV VUE_APP_FLASK_HOST=${VUE_APP_FLASK_HOST}
ENV VUE_APP_FLASK_PORT=${VUE_APP_FLASK_PORT}
ENV VUE_APP_FRONTEND_HOST=${VUE_APP_FRONTEND_HOST}
ENV VUE_APP_FRONTEND_PORT=${VUE_APP_FRONTEND_PORT}

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# production stage
FROM nginx:stable-alpine AS production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]