services:
  psql-db:
    image: postgres:16
    container_name: profiler-insight-psql-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=profilerDB
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 20s
      retries: 5

  profiler-insight-frontend:
    image: sanderbos/profiler-insight-frontend:0.4.0
    container_name: profiler-insight-frontend
    depends_on:
      - profiler-insight
    ports:
      - 8080:80

  profiler-insight:
    image: sanderbos/profiler-insight:0.4.0
    container_name: profiler-insight-backend
    depends_on:
      - psql-db
    environment:
    # databse configuration
      - databaseHost=psql-db
      - databasePort=5432
      - databaseName=profilerDB
      - databaseUser=postgres
      - databasePassword=admin
    # flask configuration 
      - SECRET_KEY=1234
      - ENCRYPTION_KEY=uzxnpF4cpPrhmz7BBkTwAevXlxWOFjdIMECIgD9Yk1M=
      - FLASK_PORT=5000
      - APP_HOST=0.0.0.0
      - FRONTEND_HOST=localhost
      - FRONTEND_PORT=8080
    ports:
      - "5000:5000"
    volumes:
      - data_db:/data_db
      - data_file:/data_file
volumes:
  db-data:
  data_db:
  data_file:


