services:
  psql-db:
    image: postgres:16
    container_name: profiler-insight-psql-db
    environment:
      - POSTGRES_USER=${databaseUser:-postgres}
      - POSTGRES_PASSWORD=${databasePassword:-admin}
      - POSTGRES_DB=${databaseName:-profilerDB}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 20s
      retries: 5

  profiler-insight-frontend:
    image: sanderbos/profiler-insight-frontend:0.0.4
    container_name: profiler-insight-frontend
    depends_on:
      - profiler-insight
    ports:
      - "${VUE_APP_FRONTEND_PORT-8080}:80"

  profiler-insight:
    image: sanderbos/profiler-insight:0.0.4
    container_name: profiler-insight-backend
    depends_on:
      - psql-db
    environment:
    # databse configuration
      - databaseHost=psql-db
      - databasePort=${databasePort:-5432}
      - databaseName=${databaseName:-profilerDB}
      - databaseUser=${databaseUser:-postgres}
      - databasePassword=${databasePassword:-admin}
    # flask configuration 
      - SECRET_KEY=${SECRET_KEY:-mysecretkey}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY:-uzxnpF4cpPrhmz7BBkTwAevXlxWOFjdIMECIgD9Yk1M=}
    ports:
      - "${FLASK_PORT:-5000}:5000"
volumes:
  db-data:

