"""empty message

Revision ID: 8d58c5252701
Revises: 9f0b86f768fe
Create Date: 2024-06-25 15:52:58.104516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d58c5252701'
down_revision = '9f0b86f768fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_conncetions',
    sa.Column('Host', sa.Integer(), nullable=False),
    sa.Column('Port', sa.String(length=80), nullable=False),
    sa.Column('DataBase', sa.String(length=120), nullable=False),
    sa.Column('UserName', sa.String(length=80), nullable=False),
    sa.Column('Password', sa.String(length=80), nullable=False),
    sa.Column('DatabaseType', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('Host', 'DataBase'),
    sa.UniqueConstraint('Port')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_conncetions')
    # ### end Alembic commands ###
