"""empty message

Revision ID: 9f0b86f768fe
Revises: 
Create Date: 2024-06-25 15:41:32.754198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0b86f768fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connections')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('Host', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('Port', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('DataBase', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('Username', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('Password', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('DatabaseType', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('Host', 'Port', name='connections_pkey')
    )
    # ### end Alembic commands ###
