FROM python:3.12.4-alpine3.19

ARG FRONTEND_HOST
ARG FRONTEND_PORT
ARG FLASK_HOST
ARG FLASK_PORT

RUN apk update && \
    apk add --no-cache \
        build-base \
        postgresql-dev \
        libpq

RUN mkdir /profilerApp
WORKDIR /profilerApp


COPY requirements.txt /profilerApp/
RUN pip install --no-cache-dir -r /profilerApp/requirements.txt

COPY run.py /profilerApp/
COPY src ./src

ENV FLASK_HOST=${FLASK_HOST}
ENV FLASK_PORT=${FLASK_PORT}
ENV FRONTEND_HOST=${FRONTEND_HOST}
ENV FRONTEND_PORT=${FRONTEND_PORT}
ENV SECRET_KEY="1234"
ENV ENCRYPTION_KEY="uzxnpF4cpPrhmz7BBkTwAevXlxWOFjdIMECIgD9Yk1M="

EXPOSE 5000
CMD ["python", "run.py"]

